import 'vue-awesome/icons/info-circle'
import 'vue-awesome/icons/sort-desc'
import 'vue-awesome/icons/trash-o'
import 'vue-awesome/icons/times-circle'
import 'vue-awesome/icons/asterisk'
import 'vue-awesome/icons/check'
import 'vue-awesome/icons/cog'
import 'vue-awesome/icons/sign-in'
import 'vue-awesome/icons/user-circle-o'
import 'vue-awesome/icons/picture-o'
import 'vue-awesome/icons/search'
import 'vue-awesome/icons/pencil'
import 'vue-awesome/icons/archive'
import 'vue-awesome/icons/refresh'
import 'vue-awesome/icons/caret-left'
import 'vue-awesome/icons/caret-right'
// import 'vue-awesome/icons/arrow-up'
// import 'vue-awesome/icons/arrow-down'
// import 'vue-awesome/icons/camera'
